export enum ExchangeActionType {
    EXCHANGE_GET_ALL_REQUEST = 'EXCHANGE_GET_ALL_REQUEST',
    EXCHANGE_GET_ALL_SUCCESS = 'EXCHANGE_GET_ALL_SUCCESS',
    EXCHANGE_GET_ALL_FAIL = 'EXCHANGE_GET_ALL_FAIL',
}