export enum WalletActionType {
    WALLET_GET_ALL_REQUEST = 'WALLET_GET_ALL_REQUEST',
    WALLET_GET_ALL_SUCCESS = 'WALLET_GET_ALL_SUCCESS',
    WALLET_GET_ALL_FAIL = 'WALLET_GET_ALL_FAIL',

    WALLET_GET_ALL_ORDER_BY_FAVORITE_REQUEST = 'WALLET_GET_ALL_ORDER_BY_FAVORITE_REQUEST',
    WALLET_GET_ALL_ORDER_BY_FAVORITE_SUCCESS = 'WALLET_GET_ALL_ORDER_BY_FAVORITE_SUCCESS',
    WALLET_GET_ALL_ORDER_BY_FAVORITE_FAIL = 'WALLET_GET_ALL_ORDER_BY_FAVORITE_FAIL',

    WALLET_UPDATE_ISFAVORITE_REQUEST = 'WALLET_UPDATE_ISFAVORITE_REQUEST',
    WALLET_UPDATE_ISFAVORITE_SUCCESS = 'WALLET_UPDATE_ISFAVORITE_SUCCESS',
    WALLET_UPDATE_ISFAVORITE_FAIL = 'WALLET_UPDATE_ISFAVORITE_FAIL',

    WALLET_CREATE_REQUEST = 'WALLET_CREATE_REQUEST',
    WALLET_CREATE_SUCCESS = 'WALLET_CREATE_SUCCESS',
    WALLET_CREATE_FAIL = 'WALLET_CREATE_FAIL'

    
}